ent-MusicTapeTest = кассета "Title 3"
    .desc = Музыкальная кассета, содержит музыку из глубин космоса.
ent-MusicTapeEnd = кассета "Виктор Цой - Кончится лето"
    .desc = Новая кассета, старый шедевр.
ent-MusicTapeNewFuture = кассета "WR∆TH ØF †HE GØDS - Новое будующее"
    .desc = Музыкальная кассета с одновременно звонкой и мягкой мелодией.
ent-MusicTapeAutumnInTheCamps = кассета "Бутырка - Осень в лагерях"
    .desc = Тюремные частушки, что может быть лучше.
ent-MusicTapeInAnOrdinaryCity = кассета "Ураган - В обыкновенном городе"
    .desc = Рок музыка с настроением старого земного города.
ent-MusicTapeNeverByAloneChapaRmx = кассета "Shadrow - Never Be Alone, Remix by - WR∆TH ØF †HE GØDS"
    .desc = При прослушивании в голове всплывает образ большого робота-медведя.                
ent-MusicTapeChapaNukeThemePianoRmx = кассета "WR∆TH ØF †HE GØDS - Nuke theme piano remix"
    .desc = Бодрое ощущение что вам пиздец.
ent-MusicTapeEnAnigmaticEncounter = кассета "Bub8les - En anigmatic encounter"
    .desc = Крутая мелодия из крутого мода.  
ent-MusicTapeSpacStacChapaRmx = кассета "Spac stac WR∆TH ØF †HE GØDS remix"
    .desc = Музыка из глубин космоса.
ent-MusicTapeAlTheThingsSheeSaid = кассета "Тату - Al the things shee said"
    .desc = Бодрая песня с бодрым текстом.
ent-MusicTapeSpaceAssholeChapaRmx = кассета "Крис Ремо - Space Asshole WR∆TH ØF †HE GØDS remix"
    .desc = Космическая жопная дыра.               